### ISSUE TITLE
🚘 Project Roadmap   

### ISSUE THREAD

**Issue by Iamkaranja** [stephaniegithinji/ticketingapp#2]
### Track all of your project work by using these **`keys`**

⛰ Epics - overarching initiatives.

🏃‍♂️ Sprints - time-bounded pushes to complete a set of tasks.

🔨 Tasks 

:electric_plug:  updates

🐞 Bugs - fix things.

 🙌 - Completed

🤘 - Brainstormed ideas
--------------------
- [x]  🏃‍♂️ Sign up / Login / logout `🔨 -> 🐞 ->  🙌`

     1. Signup/Signing-in & session retention, logout functionality `modals can now receive error/success alerts in view without losing focus` :tada: 
     2. :new:  Adjusted db schema with new tables
     3. Events creation `poster upload + validations`

#### 🏃‍♂️Buy ticket 
- [x] Generate tickets by unique Id's `🔨 -> In Progress 🌀`
        - [ ] Receive tickets via email in QR codes `Up Next`
        - [ ] Implement expiry/consumed basis
        - [ ] Buy tickets via Mpesa `⛰`

- [x] 🏃‍♂️ View booking history/previous events for use  `Up Next`

- [x]   🏃‍♂️ Also brainstorm suggest report mechanism for Admin... Feel free to add yours

- [x] 🏃‍♂️Search events (currently considering only this criteria **`month`**  , **`name`**, **`type`**)
